/**
 * What every `iconExtended` code means, in English.
 *
 * The forecast response carries the code but not its wording, so the text
 * comes from `WeatherExtended/icons.json` in the weather icon set on
 * https://platform.infoplaza.com/docs/assets/icon-sets - the same download the
 * SVGs in public/weather-icons/ come from. That file also ships Dutch, and a
 * shorter `translation_9` variant for tight spaces, both left out here.
 *
 * A code is a condition (A001 sunny, G003 snow showers) plus a D or N suffix
 * for the day and the night rendering of it, which is why "Sunny" and "Clear"
 * are the same condition under two codes.
 */

/** The wording for one icon code, at two lengths. */
export interface Condition {
  /** Up to 20 characters, for a row or a chip. */
  label: string;
  /** Up to 40 characters, for a sentence. */
  description: string;
}

/** Every code the extended icon set defines, keyed by `iconExtended`. */
export const CONDITIONS: Record<string, Condition> = {
  A001D: { label: "Plenty of sun", description: "Sunny weather" },
  A001N: { label: "Clear", description: "Clear, no clouds" },
  A002D: { label: "Sunny, also clouds", description: "Lots of sun, some clouds" },
  A002N: { label: "Mostly clear", description: "Mostly clear" },
  A003D: { label: "Both sun and clouds", description: "Both sun and clouds" },
  A003N: { label: "Some clouds", description: "Mostly clear, some clouds" },
  A004D: { label: "Cloudy, also sun", description: "Lots of clouds and some sun" },
  A004N: { label: "Often cloudy", description: "Considerable cloudy" },
  A005D: { label: "Cloudy", description: "Cloudy" },
  A005N: { label: "Cloudy", description: "Cloudy" },
  A006D: { label: "Sun and veil clouds", description: "Lots of sun, also veil clouds" },
  A006N: { label: "Veil clouds", description: "Mostly clear, veil clouds" },
  A007D: { label: "Veil clouds", description: "Veil Clouds, also sun" },
  A007N: { label: "Veil clouds", description: "Veil clouds" },
  B001D: { label: "Mist and sun", description: "Misty, but also sun" },
  B001N: { label: "Mist", description: "Misty and night clearings" },
  B002D: { label: "Fog patches and sun", description: "Fog patches, but also sun" },
  B002N: { label: "Fog patches", description: "Fog patches and some clearings" },
  B003D: { label: "Poor visibility", description: "Poor visibility by fog or dense fog" },
  B003N: { label: "Poor visibility", description: "Poor visibility by fog or dense fog" },
  B004D: { label: "Very windy", description: "Turbulent and gusty" },
  B004N: { label: "Very windy", description: "Turbulent and gusty" },
  B005D: { label: "Very hot", description: "Very high temperatures" },
  B005N: { label: "Very hot", description: "Very high temperatures" },
  B006D: { label: "Very cold", description: "Very low temperatures" },
  B006N: { label: "Very cold", description: "Very low temperatures" },
  C001D: { label: "Risk of a shower", description: "Sunny spells and risk of a shower" },
  C001N: { label: "Risk of a showers", description: "Mostly clear and chance of a shower" },
  C002D: { label: "Sun and a shower", description: "Sun, but also risk of showers" },
  C002N: { label: "Some showers", description: "Mostly clear, but also a single shower" },
  C003D: { label: "Risk heavy showers", description: "Heavy showers possible" },
  C003N: { label: "Heavy showers", description: "Heavy showers possible" },
  C004D: { label: "Downpoor possible", description: "Downpoor possible" },
  C004N: { label: "Rainburst possible", description: "Rainburst possible" },
  C005D: { label: "Showers with gusts", description: "Showers with (heavy) gusts" },
  C005N: { label: "Showers with gusts", description: "Showers with (heavy) gusts" },
  D001D: { label: "Cloudy and drizzle", description: "Cloudy with some drizzle" },
  D001N: { label: "Cloudy and drizzle", description: "Cloudy with some drizzle" },
  D002D: { label: "Cloudy and some rain", description: "Cloudy with some rain" },
  D002N: { label: "Cloudy and some rain", description: "Cloudy with some rain" },
  D003D: { label: "Cloudy and rain", description: "Rainy weather" },
  D003N: { label: "Cloudy and rain", description: "Cloudy and some time rain" },
  D004D: { label: "Strong rainfall", description: "Cloudy and strong rainfall" },
  D004N: { label: "Cloudy, lots of rain", description: "Cloudy and heavy rainfall" },
  D005D: { label: "Rain and wind", description: "Rain with a lot of wind" },
  D005N: { label: "Rain and wind", description: "Rain with a lot of wind" },
  E001D: { label: "Sleet showers", description: "Minor shower with rain and snow" },
  E001N: { label: "Sleet showers", description: "Minor shower with rain and snow" },
  E002D: { label: "Sleet showers", description: "Showers with mix of rain and sniew" },
  E002N: { label: "Sleet showers", description: "Rain and snow showers" },
  E003D: { label: "Sleet showers", description: "Heavy showers with rain and snow" },
  E003N: { label: "Sleet showers", description: "Heavy showers with rain and snow" },
  E004D: { label: "Sleet showers", description: "Heavy showers with rain and snow" },
  E004N: { label: "Sleet showers", description: "Heavy showers with rain and snow" },
  E005D: { label: "Sleet and wind", description: "Showers with rain, snow and wind" },
  E005N: { label: "Sleet and wind", description: "Showers with rain, snow and wind" },
  F001D: { label: "Light sleet", description: "Risk of rain and snow" },
  F001N: { label: "Little sleet", description: "Mix of rain and snow" },
  F002D: { label: "Cloudy with sleet", description: "Cloudy with rain and snow" },
  F002N: { label: "Cloudy with sleet", description: "Cloudy with rain and snow" },
  F003D: { label: "Cloudy with sleet", description: "Cloudy with a mix of rain and snow" },
  F003N: { label: "Cloudy with sleet", description: "Cloudy with a mix of rain and snow" },
  F004D: { label: "Lots of rain or snow", description: "Cloudy and lots of rain or sleet" },
  F004N: { label: "Lots of rain or snow", description: "Cloudy and lots of rain or sleet" },
  F005D: { label: "Sleet and wind", description: "Cloudy with rain, snow and a lot of wind" },
  F005N: { label: "Sleet and wind", description: "Cloudy with rain, snow and a lot of wind" },
  F006D: { label: "Freezing rain", description: "Slippery due to freezing rain possible" },
  F006N: { label: "Freezing rain", description: "Slippery due to freezing rain possible" },
  G001D: { label: "Sun with risk snow", description: "Sun and risk of a snow shower" },
  G001N: { label: "Clear, some snow", description: "Mostly clear and chance of a snow shower" },
  G002D: { label: "Sun and snow shower", description: "Sun, but also a single snow shower" },
  G002N: { label: "Clear,  snow showers", description: "Mostly clear, with several snow showers" },
  G003D: { label: "Snow showers and sun", description: "Snow showers possible" },
  G003N: { label: "Snow showers", description: "Snow showers possible" },
  G004D: { label: "Heavy snow showers", description: "Heavy snow showers possible" },
  G004N: { label: "Heavy snow showers", description: "Heavy snow showers possible" },
  G005D: { label: "Snow showers / wind", description: "Snow showers with (heavy) gusts" },
  G005N: { label: "Snow showers / wind", description: "Snow showers with (heavy) gusts" },
  H001D: { label: "Light snowfall", description: "Cloudy with some light snowfall" },
  H001N: { label: "Light snowfall", description: "Cloudy with some light snowfall" },
  H002D: { label: "Some snowfall", description: "Cloudy with some snowfall" },
  H002N: { label: "Some snowfall", description: "Cloudy with some snowfall" },
  H003D: { label: "Cloudy and snowfall", description: "Cloudy and snowfall at times" },
  H003N: { label: "Cloudy and snowfall", description: "Cloudy and snowfall at times" },
  H004D: { label: "Heavy snowfall", description: "Cloudy and heavy snowfall" },
  H004N: { label: "Heavy snowfall", description: "Cloudy and heavy snowfall" },
  H005D: { label: "Blizzard", description: "Blizzard" },
  H005N: { label: "Blizzard", description: "Blizzard" },
  I001D: { label: "Sleet / hail", description: "Light shower with rain, snow and hail" },
  I001N: { label: "Sleet / hail", description: "Minor shower with rain, snow and hail" },
  I002D: { label: "Sleet / hail", description: "Showers with rain, snow and hail" },
  I002N: { label: "Sleet / hail", description: "Showers with rain, snow and hail" },
  I003D: { label: "Wintry showers", description: "Heavy showers with rain, snow and hail" },
  I003N: { label: "Wintry showers", description: "Heavy showers with rain, snow and hail" },
  I004D: { label: "Wintry storms", description: "Heavy showers with rain, snow and hail" },
  I004N: { label: "Wintry storms", description: "Heavy showers with rain, snow and hail" },
  I005D: { label: "Wintry shower/wind", description: "Showers with rain, snow, hail and wind" },
  I005N: { label: "Wintry shower/wind", description: "Showers with rain, snow, hail and wind" },
  J001D: { label: "Wintry mix", description: "Some rain, snow or hail" },
  J001N: { label: "Wintry mix", description: "Some rain, snow or hail" },
  J002D: { label: "Wintry mix", description: "Cloudy with rain / snow, sometimes hail" },
  J002N: { label: "Wintry mix", description: "Cloudy with rain / snow, sometimes hail" },
  J003D: { label: "Wintry mix", description: "Mixture of rain, snow and sometimes hail" },
  J003N: { label: "Wintry mix", description: "Mixture of rain, snow and sometimes hail" },
  J004D: { label: "Wintry mix", description: "Lots of rain or sleet, also hail" },
  J004N: { label: "Wintry mix", description: "Lots of rain or sleet, also hail" },
  J005D: { label: "Sleet and wind", description: "Wintry precipitation, hail and windy" },
  J005N: { label: "Sleet and wind", description: "Wintry precipitation, hail and windy" },
  K001D: { label: "Risk thunderstorm", description: "Risk thunderstorm, also sun" },
  K001N: { label: "Risk thunderstorm", description: "Some thunderstorms possible" },
  K002D: { label: "Risk thunderstorms", description: "Risk thunderstorms, sometimes sun" },
  K002N: { label: "Risk thunderstorms", description: "Thunderstorms possible" },
  K003D: { label: "Rain, thunder, hail", description: "Thunderstorm with a chance of hail" },
  K003N: { label: "Rain, thunder, hail", description: "Thunderstorm with a chance of hail" },
  K004D: { label: "Rain, thunder, hail", description: "Heavy thunderstorm, chance of hail" },
  K004N: { label: "Rain, thunder, hail", description: "Heavy thunderstorm, chance of hail" },
  K005D: { label: "Wintry thunderstorm", description: "Wintry showers, thunder and hail" },
  K005N: { label: "Wintry thunderstorm", description: "Wintry showers, thunder and hail" },
  K006D: { label: "Wintry thunderstorm", description: "Wintry showers, thunder and hail" },
  K006N: { label: "Wintry thunderstorm", description: "Wintry showers, thunder and hail" },
  K007D: { label: "Thunderstorm / snow", description: "Snow showers with a risk of thunder" },
  K007N: { label: "Thunderstorm / snow", description: "Snow showers with a risk of thunder" },
  K008D: { label: "Thunderstorm / snow", description: "Heavy snow showers, a risk of thunder" },
  K008N: { label: "Thunderstorm / snow", description: "Heavy snow showers, a risk of thunder" },
  L001D: { label: "Risk thunderstorm", description: "Risk thunderstorm, also sun" },
  L001N: { label: "Risk thunderstorm", description: "Cloudy and a risk of a thunderstorm" },
  L002D: { label: "Risk thunderstorms", description: "Risk thunderstorms, sometimes sun" },
  L002N: { label: "Risk thunderstorms", description: "Cloudy and a risk of thunderstorms" },
  L003D: { label: "Rain, thunder, hail", description: "Cloudy, showers with thunder and hail" },
  L003N: { label: "Rain, thunder, hail", description: "Cloudy, showers with thunder and hail" },
  L004D: { label: "Rain, thunder, hail", description: "Cloudy, showers with thunder and hail" },
  L004N: { label: "Rain, thunder, hail", description: "Cloudy, showers with thunder and hail" },
  L005D: { label: "Thunder / wintry mix", description: "Wintry mix with risk of thunder" },
  L005N: { label: "Thunder / wintry mix", description: "Wintry mix with risk of thunder" },
  L006D: { label: "Thunder / wintry mix", description: "Wintry mix with risk of thunder" },
  L006N: { label: "Thunder / wintry mix", description: "Wintry mix with risk of thunder" },
  L007D: { label: "Thunderstorm / snow", description: "Cloudy and snow with a risk of thunder" },
  L007N: { label: "Thunderstorm / snow", description: "Cloudy and snow with a risk of thunder" },
  L008D: { label: "Thunderstorm / snow", description: "Heavy snowfall with a risk of thunder" },
  L008N: { label: "Thunderstorm / snow", description: "Heavy snowfall with a risk of thunder" },
  M001D: { label: "Thunderstorm / gusts", description: "Showers and wind, sometimes thunder" },
  M001N: { label: "Thunderstorm / gusts", description: "Showers and wind, sometimes thunder" },
  M002D: { label: "Thunderstorm / gusts", description: "Rain and wind, sometimes thunder / hail" },
  M002N: { label: "Thunderstorm / gusts", description: "Rain and wind, sometimes thunder / hail" },
  M003D: { label: "Thunderstorm / gusts", description: "Wintry mix, also wind and thunder" },
  M003N: { label: "Thunderstorm / gusts", description: "Wintry mix, also wind and thunder" },
  M004D: { label: "Snow, thunder, wind", description: "Snow/wind, also risk thunder/hail" },
  M004N: { label: "Snow, thunder, wind", description: "Snow/wind, also risk thunder/hail" },
  M005D: { label: "Thunderstorm / gusts", description: "Cloudy, rain and wind, risk thunder" },
  M005N: { label: "Thunderstorm / gusts", description: "Cloudy, rain and wind, risk thunder" },
  M006D: { label: "Thunderstorm / gusts", description: "Rain / wind, risk thunder and hail" },
  M006N: { label: "Thunderstorm / gusts", description: "Rain / wind, risk thunder and hail" },
  M007D: { label: "Thunderstorm / gusts", description: "Wintery precip, wind and thunder" },
  M007N: { label: "Thunderstorm / gusts", description: "Wintery precip, wind and thunder" },
  M008D: { label: "Snow, thunder, wind", description: "Snow/wind, also risk thunder" },
  M008N: { label: "Snow, thunder, wind", description: "Snow/wind, also risk thunder" },
};

/**
 * The wording for an icon code, or null when the code is missing or unknown -
 * `currently` carries no `iconExtended` at all, for instance.
 */
export function condition(iconExtended: string | undefined): Condition | null {
  if (!iconExtended) return null;
  return CONDITIONS[iconExtended] ?? null;
}
